### ISSUE TITLE
Crash on startup

### ISSUE THREAD

**Issue by Spiderach** [ApexStudios-Dev/InfusedFoods#1]
Crash Report:
[crash-2022-07-16_13.03.12-fml.txt](https://github.com/ApexStudios-Dev/InfusedFoods/files/9126331/crash-2022-07-16_13.03.12-fml.txt)

Granted, this is with about 350 mods installed so it could be a direct incompatibility, but the crash report is calling out this mod specifically and disabling it resolves the issue. I'm not sure what the conflict is specifically though.

**Comment by ApexModder** [comment]
Your version of ApexCore `apexcore-1.18.2-4.8.0.jar` is outdated, Please update it to _**v4.9.0**_.
We made some breaking updates to ApexCore little while back which broke, being able to load old versions with new versions, updating to the latest mod jars should fix it.
_This shouldnt cause issues with worlds only mod loading compatability, but make backups anyways_
